Лекция 2. Гистограмма
js-tasks-ru/htmlcss-20240216_severich pull request #3
Opened 2024-03-06 19:37 UTC by pseverina

2024-03-06 19:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-06 19:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-11 14:29 UTC, GSemikozov requested changes

2024-03-11 14:29 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  padding: 16px 24px;
`16 24 24`

2024-03-11 14:29 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  text-decoration: none;
margin-top: 3px

2024-03-11 14:29 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  grid-template-columns: repeat(30, 1fr);
нет, такой грид нам здесь не подходит, количество колонок может быть разным)

2024-03-11 14:29 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  grid-template-columns: repeat(30, 1fr);
и высота 50px

2024-03-11 14:29 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  height: 50px;
не стоит, это лишнее) высоту инлайном будем задавать в процентах

2024-03-12 21:19 UTC, GSemikozov requested changes

2024-03-12 21:19 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +        <p>Total orders</p>
вот этот элемент остался без стилизации

2024-03-13 09:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-14 15:12 UTC, GSemikozov approved these changes

2024-03-14 15:12 UTC, merged